"""Created pitch class, updated relationships

Revision ID: edd1fc008dc8
Revises: 91363c759baa
Create Date: 2022-03-06 23:18:29.734169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd1fc008dc8'
down_revision = '91363c759baa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitch_category', sa.String(length=255), nullable=True),
    sa.Column('pitch_upvote', sa.Integer(), nullable=True),
    sa.Column('pitch_downvote', sa.Integer(), nullable=True),
    sa.Column('pitch_body', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'comments', 'pitches', ['pitch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_table('pitches')
    # ### end Alembic commands ###
