"""Updated pitch to show poster

Revision ID: f7e9e1987566
Revises: edd1fc008dc8
Create Date: 2022-03-07 12:45:01.797046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e9e1987566'
down_revision = 'edd1fc008dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('posted_by', sa.String(length=22), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'posted_by')
    # ### end Alembic commands ###
